version: '3.8'

services:
  random_message:
    build:
      context: .
      dockerfile: Dockerfile
    command: python random_message.py
    volumes:
      - .:/app
    restart: unless-stopped

  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: python run.py
    volumes:
      - .:/app
    restart: unless-stopped
